# Generated by Django 3.1.1 on 2020-09-28 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bot',
            options={'permissions': (('bot_publish', 'Publica un bot'),)},
        ),
    ]
