# Generated by Django 3.1.1 on 2020-10-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ED', 'Editor'), ('AD', 'Admin'), ('AG', 'Agent')], default='ED', max_length=2),
        ),
    ]
