# Generated by Django 3.1.1 on 2020-10-05 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bot',
            options={'permissions': (('publish_bot', 'Can publish a bot'),)},
        ),
    ]
