# Generated by Django 3.1.1 on 2020-10-01 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_company_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='created_by',
        ),
    ]
